# Generated by Django 3.0.5 on 2020-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Games', 'Games'), ('PC', 'PC'), ('Anarcho-capitalism', 'Anarcho-capitalism'), ('History', 'History'), ('News', 'News')], max_length=256, null=True),
        ),
    ]
