# Generated by Django 3.0.5 on 2020-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Games', 'Games'), ('PC', 'PC'), ('Anarcho-capitalism', 'Anarcho-capitalism'), ('History', 'History'), ('News', 'News')], default='Games', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='upd_date',
            field=models.DateTimeField(null=True),
        ),
    ]
